---
name: Release

on:
  push:
    tags: ['v[0-9]+.[0-9]+.[0-9]+*']

jobs:
  run:
    name: "Build and Release Tile"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Parse Tag Name
        id: vars
        run: echo ::set-output name=tag_name::${GITHUB_REF#refs/*/}

      - name: Bake Tile
        env:
          KILN_VERSION: 0.83.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TILE_VERSION: ${{ steps.vars.outputs.tag_name }}
        run: .github/tasks/bake.sh

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: '*.pivotal'
