---
name: Test

on:
  pull_request:

jobs:
  run:
    name: "Build and Release Tile"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Version
        id: version
        run: |
          echo "build_version=$(cat "${GITHUB_WORKSPACE}/version")-build" >> "${GITHUB_OUTPUT}"

      - name: Bake Tile
        env:
          KILN_VERSION: 0.83.0
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TILE_VERSION: ${{ steps.version.outputs.build_version }}
        run: .github/tasks/bake.sh
